name: Bandit Security Scan (Python)

on:
  push:
    branches:
      - main
      - '**' # Optional: Enable for all branches

jobs:
  bandit-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Replace with the Python version your project uses

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: bandit -r .  # Scans the entire repository for security issues